package main

import "testing"

// This file exists to make sure that test coverage gets generated by goverage
// TODO remove this when there are actual tests that have actual coverage
func TestNothingInParticular(t *testing.T) {
	t.Log("Remove this test!")
}
