// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-19 12:56:00.554432776 -0700 PDT m=+0.004007788
package cmd

const GITVERSION = `7e50775 Merge branch 'niamh/readme-update' into 'release'`
const SEMVER = "1.1.0"
const DEPENDENCIES = `module gitlab.com/elixxir/gateway

go 1.13

require (
	github.com/golang/protobuf v1.4.2
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/mitchellh/go-homedir v1.1.0
	github.com/mitchellh/mapstructure v1.3.0 // indirect
	github.com/pelletier/go-toml v1.7.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/smartystreets/assertions v1.1.0 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/spf13/viper v1.6.3
	gitlab.com/elixxir/comms v0.0.0-20200515224930-70f6bb6f67f2
	gitlab.com/elixxir/crypto v0.0.0-20200518174417-c70257faa82f
	gitlab.com/elixxir/primitives v0.0.0-20200519194135-663e6a8eef55
	google.golang.org/grpc v1.29.1
	gopkg.in/ini.v1 v1.55.0 // indirect
)
`
