// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-07-13 15:19:34.5467779 -0700 PDT m=+0.053652201
package cmd

const GITVERSION = `842d8f6 run make`
const SEMVER = "1.3.2"
const DEPENDENCIES = `module gitlab.com/elixxir/gateway

go 1.13

require (
	github.com/golang/protobuf v1.4.2
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/mitchellh/mapstructure v1.3.0 // indirect
	github.com/pelletier/go-toml v1.7.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/smartystreets/assertions v1.1.0 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/spf13/viper v1.6.3
	gitlab.com/elixxir/comms v0.0.0-20200713211810-fc01d622fa7f
	gitlab.com/elixxir/crypto v0.0.0-20200707005343-97f868cbd930
	gitlab.com/elixxir/primitives v0.0.0-20200706165052-9fe7a4fb99a3
	gitlab.com/xx_network/comms v0.0.0-20200710221038-0746770adb7c
	google.golang.org/grpc v1.30.0
	gopkg.in/ini.v1 v1.55.0 // indirect
)
`
